[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    olikraus/U8g2@^2.36.18
    adafruit/Adafruit BME280 Library@^2.3.0
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.2

upload_protocol = esp-prog

debug_tool = esp-prog
debug_speed = 1000

debug_extra_cmds =
    set ESP32_ONLYCPU 1

monitor_speed = 115200

build_flags =
    -I src